name: Create multiple Issues when user story is created
on:
  issues:
    types: [opened]

jobs:
  add-issue:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          labeled: bug
