name: Create multiple Issues when user story is created
on:
  issues:
    types: [opened]

jobs:
  add-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add Issue
      run: |
        echo "Adding issue to repository..."
        cat ISSUE_TEMPLATE.md >> $GITHUB_EVENT_PATH
